### PR TITLE
feat: organize smart contracts file structures

### PR DESCRIPTION
**Pull request by Josue19-08**
A structure was created for the contracts in Soroban. Each contract (semaphore_key_pts, verifier, group) has its own subdirectory under contracts/, with its configuration in Cargo.toml and its code in src/lib.rs.
https://github.com/ZencypherSolutions/semaphore-stellar-contracts/issues/17

### CODE REVIEW

**Comment by evgongora** [comment]
Good job so far! Just missing structuring the main Semaphore contract and organizing the Semaphore group contract

**Comment by Josue19-08** [comment]
@evgongora Could review again, please.

**Review by evgongora — APPROVED** [review]
LGTM! Thank you so much :)

**Comment by evgongora** [comment]
There's a slight issue with the commits since they are not signed we can not merge the PR.

Check the following guide to have verified commits:
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification

We'll change the rule for your PR, however we'd appreciate you follow the guide so that for future contributions you have the signed commits!

**Comment by Josue19-08** [comment]
Thank you very much Sir, sorry I had not read the topic of the guides for verified commits.

**Pull request merged**
