### PR TITLE
feat: implement protocol 22 

### LINKED ISSUE #15: [Semaphore Integration] Issue 5: Implement Protocol 22 to Semaphore Groups contract
This contract manages the group (e.g., a Merkle tree of user commitments) and handles:

bls12_381_hash_to_g1:
Hash user commitments (e.g., public keys or identity credentials) to curve points when adding them to the Merkle tree.
Use this to compute hashed inputs for verification.

References
https://github.com/worldcoin/semaphore-rs/tree/main/crates/trees/src/imt
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0059.md

### PR DESCRIPTION
**Pull request by kien6034**
Closes #15

### CODE REVIEW

**Comment by kien6034** [comment]
Hi @evgongora ,

I've put together this boilerplate implementation along with some basic functionality for the Merkle tree. I'm fairly new to this (just started learning in the past few days), so I would really appreciate it if you could review it and let me know if I'm heading in the right direction. 

Any feedback or suggestions would be greatly appreciated!

**Comment by evgongora** [comment]
Hey @kien6034 so far so good, keep up the good work!

**Comment by kien6034** [comment]
@evgongora i think it is ready, tests with imt tree looks good  (in the `imt.rs` file)

can you help me review this PR 

Note: please ignore changes in `semaphore/` folder, changes happen after the restructure repo PR, but the contents are the same

**Comment by evgongora** [comment]
This is great, everything looks good so far and we will continue testing from here, thank you so much for your assistance with this issue and feel free to apply to others if you want to continue helping with this integration!

**Review by evgongora — APPROVED** [review]
This is great, everything looks good so far and we will continue testing from here, thank you so much for your assistance with this issue and feel free to apply to others if you want to continue helping with this integration!

**Pull request merged**
