### PR TITLE
feat: semaphore group contract implementation

### LINKED ISSUE #1: feat: Implement Semaphore Groups contract
Migrate the Semaphore Groups contract to Soroban.

Resource: https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/SemaphoreGroups.sol
https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/interfaces/ISemaphoreGroups.sol

### PR DESCRIPTION
**Pull request by KoxyG**
Closes #1 

Hi @bitfalt I am done with contract. Kindly review

I also worked on the test too, just for me to be to be sure my contract works. 

Kindly pls assign me the test issue, so i can push and create a pull request for the test i worked on.

### CODE REVIEW

**Comment by evgongora** [comment]
Hello @KoxyG, so far how are you dealing with the Incremental Merkle Tree?
https://zkkit.pse.dev/modules/_zk_kit_lean_imt.html

**Comment by KoxyG** [comment]
> Hello @KoxyG, so far how are you dealing with the Incremental Merkle Tree? https://zkkit.pse.dev/modules/_zk_kit_lean_imt.html

Hi @evgongora yes i saw this, but i also saw that there is no cargo package, that was why i worked on the contract without it. 

Do you have a cargo package that i can use for soroban?.

**Comment by evgongora** [comment]
> > Hello @KoxyG, so far how are you dealing with the Incremental Merkle Tree? https://zkkit.pse.dev/modules/_zk_kit_lean_imt.html
> 
> Hi @evgongora yes i saw this, but i also saw that there is no cargo package, that was why i worked on the contract without it.
> 
> Do you have a cargo package that i can use for soroban?.

This is part of the research and implementation process, we need to be able to migrate the contract inluding the IMT since is part of the Semaphore base contracts, let me know what you're able to find.

**Comment by KoxyG** [comment]
> > > Hello @KoxyG, so far how are you dealing with the Incremental Merkle Tree? https://zkkit.pse.dev/modules/_zk_kit_lean_imt.html
> > 
> > 
> > Hi @evgongora yes i saw this, but i also saw that there is no cargo package, that was why i worked on the contract without it.
> > Do you have a cargo package that i can use for soroban?.
> 
> This is part of the research and implementation process, we need to be able to migrate the contract inluding the IMT since is part of the Semaphore base contracts, let me know what you're able to find.

I see this is the TypeScript source code for the package https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/lean-imt. What I suggest is to first migrate this package , publish it, and then implement it in the Semaphore group contract.

**Comment by evgongora** [comment]
> > > > Hello @KoxyG, so far how are you dealing with the Incremental Merkle Tree? https://zkkit.pse.dev/modules/_zk_kit_lean_imt.html
> > > 
> > > 
> > > Hi @evgongora yes i saw this, but i also saw that there is no cargo package, that was why i worked on the contract without it.
> > > Do you have a cargo package that i can use for soroban?.
> > 
> > 
> > This is part of the research and implementation process, we need to be able to migrate the contract inluding the IMT since is part of the Semaphore base contracts, let me know what you're able to find.
> 
> I see this is the TypeScript source code for the package https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/lean-imt. What I suggest is to first migrate this package , publish it, and then implement it in the Semaphore group contract.

Awesome! let's do that.

**Comment by KoxyG** [comment]
> > > > > Hello @KoxyG, so far how are you dealing with the Incremental Merkle Tree? https://zkkit.pse.dev/modules/_zk_kit_lean_imt.html
> > > > 
> > > > 
> > > > Hi @evgongora yes i saw this, but i also saw that there is no cargo package, that was why i worked on the contract without it.
> > > > Do you have a cargo package that i can use for soroban?.
> > > 
> > > 
> > > This is part of the research and implementation process, we need to be able to migrate the contract inluding the IMT since is part of the Semaphore base contracts, let me know what you're able to find.
> > 
> > 
> > I see this is the TypeScript source code for the package https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/lean-imt. What I suggest is to first migrate this package , publish it, and then implement it in the Semaphore group contract.
> 
> Awesome! let's do that.

okay then

**Comment by bitfalt** [comment]
hiii @KoxyG, we'll merge your PR since the implementation is done. We'll create another issue to "create" the IMT and another one to implement it in the smart contract. 

We'll leave the tests pending until the IMT is done in the smart contract. 

Thank you for this amazing job!

**Review by bitfalt — COMMENTED** [review]
Amazing job overall, merging PR and focusing on the IMT on our side.

**Review by bitfalt — APPROVED** [review]

**Pull request merged**
